### ISSUE TITLE
Vytovrenie GUI aplikacie

### ISSUE THREAD

**Issue by cephems1** [TIS2024-FMFI/kolmogorov#13]

**Comment by cephems1** [comment]
- [x] vybrat vhodny nastoj na vytvorenie prototipu 
- [x] vytvorit maketu toho ako by to mohlo vyzerat
- [ ]  vylepsit to
- [ ]  iterovat kroky 2 a 3 pokim to nebude dobre

**Comment by Ivanusykova** [comment]
https://app.moqups.com/AEAgsJYovddt9e4aO1ii39YnMQCBEbpZ/edit/page/a14aad45a

**Comment by Ivanusykova** [comment]
https://app.moqups.com/AEAgsJYovddt9e4aO1ii39YnMQCBEbpZ/view/page/a14aad45a

**Comment by Ivanusykova** [comment]
![Image](https://github.com/user-attachments/assets/72646ee9-1449-4f90-8ad6-70cabee48312)
![Image](https://github.com/user-attachments/assets/681a2237-4d5d-4ea9-8512-ba813bf45f4d)
![Image](https://github.com/user-attachments/assets/e7c9a293-2994-49d1-ba26-1e17c67db030)
![Image](https://github.com/user-attachments/assets/d974f3e8-c1ab-416f-8145-9c8571d20e43)
![Image](https://github.com/user-attachments/assets/f54ce451-3c16-485c-b2ff-be98c2ba363c)
![Image](https://github.com/user-attachments/assets/ac553e87-0a68-46fe-a706-a4ee8774191e)
![Image](https://github.com/user-attachments/assets/d124e69c-9b04-46b9-99e7-bbcd8bba723c)
![Image](https://github.com/user-attachments/assets/25480b5b-4c75-4a4f-a8fa-3e6d715deb3e)

**Comment by pavelpetrovic** [comment]
komentare:
  - prosim doplnit checkboxy/dropboxy alebo radiobuttony podla KP
  -  zvazit ci nedat teorie pod seba a kazde tvrdenie do samostatneho riadku, nielen skratku, ale aj popis

**Comment by Ivanusykova** [comment]
[GUI_2.verzia.zip](https://github.com/user-attachments/files/17791624/GUI_2.verzia.zip)

**Comment by Ivanusykova** [comment]
[GUI_3.verzia .zip](https://github.com/user-attachments/files/17812256/GUI_3.verzia.zip)

**Comment by Ivanusykova** [comment]
[GUI_4.verzia.zip](https://github.com/user-attachments/files/18080345/GUI_4.verzia.zip)

**Comment by Ivanusykova** [comment]
[GUI_4.verzia.zip](https://github.com/user-attachments/files/18083508/GUI_4.verzia.zip)
