### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by PanFilipko** [TIS2024-FMFI/kolmogorov#2]
https://www.overleaf.com/project/66fc31993316eb9aa16a9fc6

**Comment by pavelpetrovic** [comment]
tu su moje nepodstatne komentare, s ktorymi nalozte podla vlastneho uvazenia:
  - myslim, ze namiesto catalog je krajsie povedat System Requirements Specification Document
  - 1.1. binding agreement....
  - representations of mathematical relations => pod tymto som si predstavil nieco celkom ine
  - 1.3. please use bold font
  - 1.5. prosim konkretnejsie
  - 2.1. can manipulate => what do you mean?
      their => cim menej zamen, tym mensia sanca ze to zle pochopim
      that prove => contribute to one of the possible proofs
        => z toho vyplyva, ci su v mm vsetky dokazy aj vychadzajuce z roznych tvrdeni a ci by nebolo mozne pri vizualizacii zobrazovat iba niektore tvrdenia - tie ktore sa podielaju na nejakom konkretnom dokaze
         myslienky:
            - zobrazit nahodny / prvy dokaz, nie vsetky tvrdenia, ktore sa podielaju na nejakom dokaze
            - kostra
            - mat moznost konstru dynamicky menit
            - co s cyklami a ekvivalenciami
            - viac roznych rieseni najdenia teorie z ktorej vyplyva ina teoria
  - 2.2. ma byt jeden plynuly text s nadvazujucimi vetami          
  - 3.1. privelmi ambiguous, radsej presnejsie opisat
  - aj v 2. aj v 3. casti su vsetky vety cele vety (podmet, prisudok)
  - "using keywords." => utrpel som kulturny sok
  - " can be added to theory one or theory two" => opat kulturny sok
  - " on the graph." => what graph are you talking about here?
  - ak system nieco importuje alebo exportuje, treba mat presne vyspecifikovane, v akom formate (ake datove typy vsetkych poloziek) to bude - mozno pouzit odkaz na priklad takeho dokumentu, alebo subor, ktory popisuje format, alebo rovno do KP

**Comment by pavelpetrovic** [comment]
este nepodstatnejsie komentare:
 - 1.3. statement theorem ma stale pomiatlo. co je v theorem nazvat statement a pod to kurzivou dat to co je v statement
 - node ma tiez zmiatol, lebo uz raz ste definovali vertex a bolo by dobre mat konzistentnu terminologiu, LINKy by som dal prec, lebo slovo LINK znie ako hrana a tiez to tam matie
 - 2.2 "with uploading" - nerozumiem, co si pod tym mam predstavit
 - 2.2. odstavec "Next, the user..." vyvolava nejake nezodpovedane otazky a nadej v citatelovi, ze sa to dozvie neskor, ale bol by spokojnejsi, keby sa to dozvedel uz tu
 - "exported as an image" - bitmap or vector image?
 - vo vete " Data such as..."  som hodil NullPointerException na slove "needed" aj na slove "formed"
 - v dalsej vete, FileNotFoundException na "detailed information"
- 3.1.1. prosim zlucit do 3.1.2
- 3.1.5,6. importing -> selecting
- 3.1.6 je v rozpore s 3.1.7. lebo jeden validuje na "select" a druhy validuje na "submit"
- 3.2.2. "already draw graph" - nevieme co to je a odkial to prislo, minimalne treba dat krizovy odkaz na inu poziadavku
- 3.2.4.  veci, ktore nemozu byt inak netreba zdoraznovat
- 3.2.2 negacia a negacia -> search is available only when the graph is visualized
- 3.3   type I a II - could you invent more clear names?
- 3.3.1.10 "These nodes also branch out to represent the nodes that reference the original node." - very confusing sentence
- possibility to set maximum depth
- 3.3.3 suggest red-blue-purple
- suggesting mentioning that layout of nodes in one layer will be optimized for viewing, not random  (optional requirement)
- missing information about transitivity  A <- B,C   B <- C,    => B and C are not at the same layer, even though A <- B,C suggests they are
- ostavaju otazniky o tom, co vlastne su tvrdenia v metamathe a co su dokazy a ake to ma dosledky na system, treba to zistit a doplnit do dokumentu

**Comment by pavelpetrovic** [comment]
nove kolo :-)

- maybe choose a more unique marking of requirements, for example 3.3.1  is found two times in the document
- consider renaming "type 1" and "type 2" consistently with 3.3
- "The second one shows all statements proven by the defined theory."  - toto znie ako keby sa chceli zobrazit iba tie tvrdenia, ktore su dokazatelne iba pomocou tvrdeni z vybranej teorie a ziadnych inych. Ale zamer je asi iny?
- 2.1 a 2.2 "first" a "second" su naopak
- 3.2.1.f  id je to iste ako name  (aj 3.4.7)
- 3.5.4. import only theories
- 3.3.7. potrebujeme informaciu od zadavatela (a zaroven konfrontovat s datami v metamathe) ze co znamena "node is at some set
depth from the theories" - lebo od roznych statementov moze byt v roznych hlbkach
- 3.3.9. still not cleaer what this means, see image 
- 3.3.10. krizova referencia smeruje inam
- 3.3.1.13. "That means that chosen theory" => "That means that any statement in the chosen theory"
- 3.3.1. aj 3.3.2 hovori v prvej vete to iste, cize tvrdenia ktore potrebovali nejake tvrdenie z teorie vo svojom dokaze, namiesto "proved from" a "proved by" chcete jednoznacnejsie nazvy "statements supported by theory statements", "statements supporting theory statements"

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/366cd922-cd58-488e-bfad-0f92c476e2c1)

**Comment by cephems1** [comment]
https://us.metamath.org/mpeuni/pythag.html

**Comment by Ivanusykova** [comment]
[katalog_TIS.pdf](https://github.com/user-attachments/files/17659890/katalog_TIS.pdf)

**Comment by pavelpetrovic** [comment]
vymysleli sme tri nezavisle checkboxy:

vyber uzlov, ktore sa vobec do grafu zaradia (smerom hore - cize co vyplyva z teorie):

[ ] musia sa v teorii zadat aj axiomy
[ ] vsetky tvrdenia z teorie musia byt pouzite
[ ] su dovolene aj ine vychodiska ako tie, su v teorii

ked uz tam su, este je otazne, ktore hrany sa zobrazia (oboma smermi)

( ) zobraz vsetky hrany
( ) zobraz iba hrany medzi susednymi poschodiami

vyber uzlov, ktore sa vobec do grafu zaradia (smerom dole - z coho nasa teoria vyplyva):

[ ] zaradit aj axiomy
[ ] zaradit iba uzly, ktore su pouzite v dokaze kazdeho tvrdenia v teorii
N - do akej hlbky tranzitivity, napr. pre N=1 zaradi iba vrcholy, ktore su priamo pouzite v dokaze tvrdenia v teorii,
      pre N=2 take ako N=1 a aj tie, ktore su pouzite v dokazoch tvrdeni, ktore su pouzite v dokazoch tvrdeni v teorii, ...

na ktore poschodie sa uzly umiestnia:

 - ak je zaradovany vrchol aspon v dvoch roznych vzdialenostiach 
      (pocet dokazovych krokov od dokazu kedy je priamo pouzity) 
   tak sa zobrazi na poschodi:
    (  )  v najmensej vzdialenosti
    (  )  v najvacsej vzdialenosti

definicie system vobec neriesi

**Comment by Ivanusykova** [comment]
[katalog_TIS.pdf](https://github.com/user-attachments/files/17920869/katalog_TIS.pdf)
